name: McCombatLevel
main: com.gmail.mrphpfan.McCombatLevel
version: 1.2
depend: [mcMMO]

commands:
  level:
    description: See your combat level is.
    usage: /level
  combatlevel:
    description: See your combat level is.
    usage: /level